=== samerkour/XMLWinFormsSample/XMLHandlerWinFormsSample/Data/Project.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="Project" type="T_Project"/>
    <xs:complexType name="T_Project">
        <xs:sequence>
            <xs:element name="Information" type="T_Information"/>
            <xs:element name="Data" type="T_Data" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_Information">
        <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Type" type="T_ProjectType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="T_Data">
        <xs:sequence>
            <xs:element name="Value" type="xs:double" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="T_ProjectType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Unknown"/>
            <xs:enumeration value="Diagnostics"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== samerkour/XMLWinFormsSample/XMLHandlerWinFormsSample/Data/ProjectExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<Project xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Project.xsd">
    <Information>
        <Name>TestProject</Name>
        <Type>Diagnostics</Type>
    </Information>
    <Data>
        <Value>1.0</Value>
        <Value>2.0</Value>
        <Value>3.0</Value>
        <Value>4.0</Value>
        <Value>5.0</Value>
        <Value>6.0</Value>
        <Value>7.0</Value>
        <Value>8.0</Value>
        <Value>9.0</Value>
        <Value>10.0</Value>
        <Value>11.0</Value>
        <Value>12.0</Value>
        <Value>13.0</Value>
        <Value>14.0</Value>
        <Value>15.0</Value>
        <Value>16.0</Value>
        <Value>17.0</Value>
        <Value>18.0</Value>
        <Value>19.0</Value>
        <Value>20.0</Value>
        <Value>21.0</Value>
        <Value>22.0</Value>
        <Value>23.0</Value>
        <Value>24.0</Value>
        <Value>25.0</Value>
        <Value>26.0</Value>
        <Value>27.0</Value>
        <Value>28.0</Value>
        <Value>29.0</Value>
        <Value>30.0</Value>
        <Value>31.0</Value>
        <Value>32.0</Value>
        <Value>33.0</Value>
        <Value>34.0</Value>
        <Value>35.0</Value>
        <Value>36.0</Value>
        <Value>37.0</Value>
        <Value>38.0</Value>
        <Value>39.0</Value>
        <Value>40.0</Value>
        <Value>41.0</Value>
        <Value>42.0</Value>
        <Value>43.0</Value>
        <Value>44.0</Value>
        <Value>45.0</Value>
        <Value>46.0</Value>
        <Value>47.0</Value>
        <Value>48.0</Value>
        <Value>49.0</Value>
    </Data>
</Project>
